// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/tkcrm/pgxgen/utils"
	"strings"
)

type ConstantsTableNamesParamsItem struct {
	NamePreffix string
	Name        string
}

type ConstantsColumnNamesParamsItem struct {
	TableName   string
	NamePreffix string
	Name        string
}

type ConstantsParams struct {
	Package     string
	Version     string
	Tables      []ConstantsTableNamesParamsItem
	ColumnNames []ConstantsColumnNamesParamsItem
}

func (p ConstantsParams) GetColumnsForTable(tableName string) []ConstantsColumnNamesParamsItem {
	res := []ConstantsColumnNamesParamsItem{}
	for _, item := range p.ColumnNames {
		if item.TableName == tableName {
			res = append(res, item)
		}
	}
	return res
}

func (p ConstantsParams) GetHeaderComment() string {
	content := strings.Builder{}
	content.WriteString(fmt.Sprintf(`// Code generated by pgxgen. DO NOT EDIT.
// versions:
//   pgxgen %s
package %s

import (
  "strings"
  "github.com/gobeam/stringy"
)`, p.Version, p.Package))
	content.WriteString("\n")
	return content.String()
}

func (p ConstantsParams) GetTablesContent() string {
	content := strings.Builder{}
	content.WriteString(`type TableName string

func (s TableName) String() string { return string(s) }`)
	content.WriteString("\n")

	for _, item := range p.Tables {
		content.WriteString("\nconst (\n")
		content.WriteString(fmt.Sprintf(`TableName%s TableName = "%s"`, item.NamePreffix, item.Name))
		content.WriteString(")\n")
	}
	return content.String()
}

func (p ConstantsParams) GetColumnNamesContent() string {
	content := strings.Builder{}
	content.WriteString(`type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
  v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
  return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
  res := make([]string, len(s))
  for idx, colName := range s {
    res[idx] = colName.String()
  }
  return res
}`)
	content.WriteString("\nconst (\n")

	for _, item := range p.ColumnNames {
		content.WriteString(fmt.Sprintf(`ColumnName%s ColumnName = "%s"`, item.NamePreffix, item.Name))
		content.WriteString("\n")
	}
	content.WriteString(")\n\n")

	for _, tableName := range p.Tables {
		content.WriteString(fmt.Sprintf("func %sColumnNames() ColumnNames {\n", utils.ToPascalCase(tableName.Name)))
		content.WriteString("return ColumnNames{\n")
		for _, item := range p.GetColumnsForTable(tableName.Name) {
			content.WriteString(fmt.Sprintf("ColumnName%s,\n", item.NamePreffix))
		}
		content.WriteString("}\n")
		content.WriteString("}\n")
	}
	return content.String()
}

func Constatnts(p ConstantsParams) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(p.GetHeaderComment()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(p.Tables) > 0 {
			templ_7745c5c3_Err = templ.Raw(p.GetTablesContent()).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if len(p.ColumnNames) > 0 {
			templ_7745c5c3_Err = templ.Raw(p.GetColumnNamesContent()).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
