// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"fmt"
	"github.com/gobeam/stringy"
	"strings"
)

type ConstantsTableNamesParamsItem struct {
	NamePreffix string
	Name        string
}

type ConstantsColumnNamesParamsItem struct {
	TableName   string
	NamePreffix string
	Name        string
}

type ConstantsParams struct {
	Package     string
	Version     string
	Tables      []ConstantsTableNamesParamsItem
	ColumnNames []ConstantsColumnNamesParamsItem
}

func (p ConstantsParams) GetColumnsForTable(tableName string) []ConstantsColumnNamesParamsItem {
	res := []ConstantsColumnNamesParamsItem{}
	for _, item := range p.ColumnNames {
		if item.TableName == tableName {
			res = append(res, item)
		}
	}
	return res
}

func (p ConstantsParams) GetHeaderComment() string {
	content := strings.Builder{}
	content.WriteString(fmt.Sprintf(`// Code generated by pgxgen. DO NOT EDIT.
// versions:
//   pgxgen %s
package %s

import (
  "strings"
  "github.com/gobeam/stringy"
)`, p.Version, p.Package))
	content.WriteString("\n")
	return content.String()
}

func (p ConstantsParams) GetTablesContent() string {
	content := strings.Builder{}
	content.WriteString(`type TableName string

func (s TableName) String() string { return string(s) }`)
	content.WriteString("\n")

	for _, item := range p.Tables {
		content.WriteString("\nconst (\n")
		content.WriteString(fmt.Sprintf(`TableName%s TableName = "%s"`, item.NamePreffix, item.Name))
		content.WriteString(")\n")
	}
	return content.String()
}

func (p ConstantsParams) GetColumnNamesContent() string {
	content := strings.Builder{}
	content.WriteString(`type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
  v := stringy.New(string(s)).CamelCase()
	v = stringy.New(v).UcFirst()
  return strings.ReplaceAll(v, "Id", "ID")
}`)
	content.WriteString("\nconst (\n")

	for _, item := range p.ColumnNames {
		content.WriteString(fmt.Sprintf(`ColumnName%s ColumnName = "%s"`, item.NamePreffix, item.Name))
		content.WriteString("\n")
	}
	content.WriteString(")\n\n")

	for _, tableName := range p.Tables {
		content.WriteString(fmt.Sprintf("func %sColumnNames() []ColumnName {\n", stringy.New(stringy.New(tableName.Name).CamelCase()).UcFirst()))
		content.WriteString("return []ColumnName{\n")
		for _, item := range p.GetColumnsForTable(tableName.Name) {
			content.WriteString(fmt.Sprintf("ColumnName%s,\n", item.NamePreffix))
		}
		content.WriteString("}\n")
		content.WriteString("}\n")
	}
	return content.String()
}

func Constatnts(p ConstantsParams) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(p.GetHeaderComment()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(p.Tables) > 0 {
			templ_7745c5c3_Err = templ.Raw(p.GetTablesContent()).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if len(p.ColumnNames) > 0 {
			templ_7745c5c3_Err = templ.Raw(p.GetColumnNamesContent()).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
