package constants

import (
	"fmt"
	"io"
	"strings"
	"text/template"

	"github.com/tkcrm/pgxgen/utils"
)

type ConstantsTableNamesParamsItem struct {
	NamePreffix   string
	Name          string
	BareTableName string
}

type ConstantsColumnNamesParamsItem struct {
	TableName   string
	NamePreffix string
	Name        string
}

type ConstantsParams struct {
	Package     string
	Tables      []ConstantsTableNamesParamsItem
	ColumnNames []ConstantsColumnNamesParamsItem
}

func (p ConstantsParams) GetColumnsForTable(tableName string) []ConstantsColumnNamesParamsItem {
	res := []ConstantsColumnNamesParamsItem{}
	for _, item := range p.ColumnNames {
		if item.TableName == tableName {
			res = append(res, item)
		}
	}
	return res
}

func (p ConstantsParams) GetHeaderComment() string {
	content := strings.Builder{}
	fmt.Fprintf(&content, `// Code generated by pgxgen. DO NOT EDIT.
package %s
`, p.Package)
	if len(p.ColumnNames) > 0 {
		content.WriteString(`
import (
  "strings"
  "github.com/gobeam/stringy"
)
`)
	}
	content.WriteString("\n")
	return content.String()
}

func (p ConstantsParams) GetTablesContent() string {
	content := strings.Builder{}
	content.WriteString(`type TableName string

func (s TableName) String() string { return string(s) }`)
	content.WriteString("\n")

	for _, item := range p.Tables {
		content.WriteString("\nconst (\n")
		fmt.Fprintf(&content, `TableName%s TableName = "%s"`, item.NamePreffix, item.Name)
		content.WriteString(")\n")
	}
	return content.String()
}

func (p ConstantsParams) GetColumnNamesContent() string {
	content := strings.Builder{}
	content.WriteString(`type ColumnName string

func (s ColumnName) String() string { return string(s) }

func (s ColumnName) StructName() string {
  v := stringy.New(string(s)).CamelCase().Get()
	v = stringy.New(v).UcFirst()
  return strings.ReplaceAll(v, "Id", "ID")
}

type ColumnNames []ColumnName

func (s ColumnNames) Strings() []string {
  res := make([]string, len(s))
  for idx, colName := range s {
    res[idx] = colName.String()
  }
  return res
}`)
	content.WriteString("\nconst (\n")

	for _, item := range p.ColumnNames {
		fmt.Fprintf(&content, `ColumnName%s ColumnName = "%s"`, item.NamePreffix, item.Name)
		content.WriteString("\n")
	}
	content.WriteString(")\n\n")

	for _, tableName := range p.Tables {
		fmt.Fprintf(&content, "func %sColumnNames() ColumnNames {\n", utils.ToPascalCase(tableName.BareTableName))
		content.WriteString("return ColumnNames{\n")
		for _, item := range p.GetColumnsForTable(tableName.Name) {
			fmt.Fprintf(&content, "ColumnName%s,\n", item.NamePreffix)
		}
		content.WriteString("}\n")
		content.WriteString("}\n")
	}
	return content.String()
}

const constantsTmpl = `{{.GetHeaderComment}}{{if .Tables}}{{.GetTablesContent}}{{end}}{{if .ColumnNames}}{{.GetColumnNamesContent}}{{end}}`

func RenderConstants(p ConstantsParams, w io.Writer) error {
	tmpl, err := template.New("constants").Parse(constantsTmpl)
	if err != nil {
		return err
	}
	return tmpl.Execute(w, p)
}
