package genmodels

import (
	"bytes"
	"fmt"
	"go/format"
	"path/filepath"
	"strings"
	"time"

	"github.com/tkcrm/pgxgen/internal/config"
	"github.com/tkcrm/pgxgen/internal/sqlparser"
	"github.com/tkcrm/pgxgen/internal/sqlparser/catalog"
	"github.com/tkcrm/pgxgen/internal/sqlparser/typemap"
	"github.com/tkcrm/pgxgen/pkg/logger"
	"github.com/tkcrm/pgxgen/utils"
)

type genModels struct {
	logger logger.Logger
	config config.Config
}

func New(logger logger.Logger, cfg config.Config) *genModels {
	return &genModels{
		logger: logger,
		config: cfg,
	}
}

func (g *genModels) Generate() error {
	for _, cfg := range g.config.Pgxgen.Generate.Models {
		if err := cfg.Validate(); err != nil {
			return fmt.Errorf("config validation error: %w", err)
		}

		g.logger.Infof("generating models for schema: %s", cfg.SchemaDir)
		timeStart := time.Now()

		if err := g.generateForConfig(cfg); err != nil {
			return fmt.Errorf("generate models error: %w", err)
		}

		g.logger.Infof("models successfully generated in: %s", time.Since(timeStart))
	}

	return nil
}

func (g *genModels) generateForConfig(cfg config.GenerateModelsConfig) error {
	engine := cfg.Engine
	if engine == "" {
		engine = "postgresql"
	}

	parser, err := sqlparser.NewParser(engine)
	if err != nil {
		return fmt.Errorf("create parser: %w", err)
	}

	schemaDir := cfg.SchemaDir
	// Resolve relative to pgxgen config dir
	if !filepath.IsAbs(schemaDir) {
		pgxgenDir := filepath.Dir(g.config.ConfigPaths.PgxgenConfigFilePath)
		absDir, err := filepath.Abs(filepath.Join(pgxgenDir, schemaDir))
		if err != nil {
			return fmt.Errorf("resolve schema dir: %w", err)
		}
		schemaDir = absDir
	}

	files, err := sqlparser.ResolveSchemaFiles(schemaDir)
	if err != nil {
		return fmt.Errorf("resolve schema files: %w", err)
	}

	cat, err := parser.ParseSchema(files)
	if err != nil {
		return fmt.Errorf("parse schema: %w", err)
	}

	mapper, err := typemap.NewTypeMapper(engine)
	if err != nil {
		return fmt.Errorf("create type mapper: %w", err)
	}

	mapOpts := typemap.Options{
		SqlPackage:          cfg.SqlPackage,
		EmitPointersForNull: cfg.EmitPointersForNull,
	}

	code, err := g.renderModels(cfg, cat, mapper, mapOpts)
	if err != nil {
		return fmt.Errorf("render models: %w", err)
	}

	outputDir := cfg.OutputDir
	if !filepath.IsAbs(outputDir) {
		pgxgenDir := filepath.Dir(g.config.ConfigPaths.PgxgenConfigFilePath)
		absDir, err := filepath.Abs(filepath.Join(pgxgenDir, outputDir))
		if err != nil {
			return fmt.Errorf("resolve output dir: %w", err)
		}
		outputDir = absDir
	}

	if err := utils.SaveFile(outputDir, cfg.GetOutputFileName(), code); err != nil {
		return fmt.Errorf("save file: %w", err)
	}

	return nil
}

func (g *genModels) renderModels(
	cfg config.GenerateModelsConfig,
	cat *catalog.Catalog,
	mapper typemap.TypeMapper,
	mapOpts typemap.Options,
) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("// Code generated by pgxgen. DO NOT EDIT.\n"))
	buf.WriteString(fmt.Sprintf("package %s\n\n", cfg.PackageName))

	// Collect all enums across schemas for type resolution
	var allEnums []*catalog.Enum
	for _, s := range cat.Schemas {
		allEnums = append(allEnums, s.Enums...)
	}

	// Generate enums
	for _, s := range cat.Schemas {
		for _, enum := range s.Enums {
			g.renderEnum(&buf, enum)
		}
	}

	// Generate table structs
	for _, s := range cat.Schemas {
		for _, table := range s.Tables {
			g.renderStruct(&buf, cfg, table, mapper, allEnums, mapOpts)
		}
	}

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// If formatting fails, try goimports
		formatted, err = utils.UpdateGoImports(buf.Bytes())
		if err != nil {
			return nil, fmt.Errorf("format code: %w", err)
		}
	}

	// Run goimports for auto-import resolution
	result, err := utils.UpdateGoImports(formatted)
	if err != nil {
		return formatted, nil
	}

	return result, nil
}

func (g *genModels) renderEnum(buf *bytes.Buffer, enum *catalog.Enum) {
	typeName := toCamelCase(enum.Name)

	buf.WriteString(fmt.Sprintf("type %s string\n\n", typeName))
	buf.WriteString("const (\n")
	for _, val := range enum.Values {
		constName := typeName + toCamelCase(val)
		buf.WriteString(fmt.Sprintf("\t%s %s = %q\n", constName, typeName, val))
	}
	buf.WriteString(")\n\n")

	// Values method
	buf.WriteString(fmt.Sprintf("func (e %s) Valid() bool {\n", typeName))
	buf.WriteString("\tswitch e {\n")
	buf.WriteString("\tcase ")
	for i, val := range enum.Values {
		if i > 0 {
			buf.WriteString(",\n\t\t")
		}
		buf.WriteString(typeName + toCamelCase(val))
	}
	buf.WriteString(":\n")
	buf.WriteString("\t\treturn true\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn false\n")
	buf.WriteString("}\n\n")
}

func (g *genModels) renderStruct(
	buf *bytes.Buffer,
	cfg config.GenerateModelsConfig,
	table *catalog.Table,
	mapper typemap.TypeMapper,
	enums []*catalog.Enum,
	mapOpts typemap.Options,
) {
	structName := toCamelCase(table.Name)

	if table.Comment != "" {
		buf.WriteString(fmt.Sprintf("// %s %s\n", structName, table.Comment))
	}

	buf.WriteString(fmt.Sprintf("type %s struct {\n", structName))

	for _, col := range table.Columns {
		fieldName := toCamelCase(col.Name)
		fieldType := mapper.GoType(col, enums, mapOpts)

		var tags []string
		if cfg.EmitJsonTags {
			tags = append(tags, fmt.Sprintf(`json:"%s"`, col.Name))
		}
		if cfg.EmitDbTags {
			tags = append(tags, fmt.Sprintf(`db:"%s"`, col.Name))
		}

		tagStr := ""
		if len(tags) > 0 {
			tagStr = fmt.Sprintf(" `%s`", strings.Join(tags, " "))
		}

		buf.WriteString(fmt.Sprintf("\t%s %s%s\n", fieldName, fieldType, tagStr))
	}

	buf.WriteString("}\n\n")
}

// toCamelCase converts a snake_case string to CamelCase.
func toCamelCase(s string) string {
	var result strings.Builder
	upper := true
	for _, c := range s {
		if c == '_' || c == '-' || c == ' ' {
			upper = true
			continue
		}
		if upper {
			result.WriteRune(rune(strings.ToUpper(string(c))[0]))
			upper = false
		} else {
			result.WriteRune(c)
		}
	}
	return result.String()
}
