package sqlc

import (
	"testing"

	"github.com/tkcrm/pgxgen/internal/config"
)

func TestReplaceImports(t *testing.T) {
	str1 := `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package psqldb

import (
	"context"
	"time"

	. "github.com/test/testtest/internal/models"
    _ "github.com/test/testtest/internal/models"
    asdasd "github.com/test/testtest/internal/models"
)

const a = "b{})"
)
sdv

asdvvvvasdv {}`

	str2 := `// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: queries.sql

package psqldb

import "context"

const a = "b"`

	cfg := config.Config{
		Pgxgen: config.Pgxgen{
			SqlcModels: config.SqlcMoveModels{
				PackagePath: "1234",
			},
		},
	}

	replaceImports(cfg, str1)
	replaceImports(cfg, str2)
}
