package models

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/tkcrm/pgxgen/internal/config"
	"github.com/tkcrm/pgxgen/internal/sqlparser/catalog"
	"github.com/tkcrm/pgxgen/internal/sqlparser/typemap"
)

func newTestCatalog() *catalog.Catalog {
	return &catalog.Catalog{
		DefaultSchema: "main",
		Schemas: []*catalog.Schema{
			{
				Name: "main",
				Enums: []*catalog.Enum{
					{Name: "todo_status", Values: []string{"pending", "completed", "cancelled"}},
					{Name: "priority_level", Values: []string{"low", "medium", "high"}},
				},
				Tables: []*catalog.Table{
					{
						Name: "todos",
						Columns: []*catalog.Column{
							{Name: "id", Type: "TEXT", NotNull: true},
							{Name: "user_id", Type: "INTEGER", NotNull: true},
							{Name: "title", Type: "TEXT", NotNull: true},
							{Name: "description", Type: "TEXT", NotNull: true},
							{Name: "status", Type: "todo_status", NotNull: true},
							{Name: "completed_at", Type: "TIMESTAMP"},
							{Name: "created_at", Type: "TIMESTAMP", NotNull: true},
							{Name: "workspace_id", Type: "TEXT"},
						},
					},
					{
						Name: "workspaces",
						Columns: []*catalog.Column{
							{Name: "id", Type: "TEXT", NotNull: true},
							{Name: "user_id", Type: "INTEGER", NotNull: true},
							{Name: "name", Type: "TEXT", NotNull: true},
							{Name: "archived", Type: "BOOLEAN", NotNull: true},
						},
					},
					{
						Name: "note_tags",
						Columns: []*catalog.Column{
							{Name: "note_id", Type: "TEXT", NotNull: true},
							{Name: "tag_id", Type: "TEXT", NotNull: true},
						},
					},
					{
						Name:    "authors",
						Comment: "table for book authors",
						Columns: []*catalog.Column{
							{Name: "id", Type: "TEXT", NotNull: true},
							{Name: "full_name", Type: "TEXT", NotNull: true},
							{Name: "website_url", Type: "TEXT"},
						},
					},
				},
			},
		},
	}
}

func render(t *testing.T, cfg *config.ModelsConfig, cat *catalog.Catalog, sqlcOverrides *config.SqlcOverridesConfig, sqlcDefaults *config.SqlcDefaultsConfig) string {
	t.Helper()
	mapper, err := typemap.NewTypeMapper("sqlite")
	require.NoError(t, err)
	mapOpts := typemap.Options{
		SqlPackage:          "database/sql",
		EmitPointersForNull: cfg.EmitPointersForNull || cfg.ReplaceNullableTypes,
	}
	code, err := renderModelsRaw(cfg, cat, mapper, mapOpts, sqlcOverrides, sqlcDefaults)
	require.NoError(t, err)
	return string(code)
}

// --- toCamelCase ---

func TestToCamelCase(t *testing.T) {
	tests := map[string]string{
		"id":          "ID",
		"user_id":     "UserID",
		"note_id":     "NoteID",
		"created_at":  "CreatedAt",
		"full_name":   "FullName",
		"website_url": "WebsiteURL",
		"http_status": "HTTPStatus",
		"is_active":   "IsActive",
		"uuid":        "UUID",
		"json_data":   "JSONData",
		"html_body":   "HTMLBody",
		"api_key":     "APIKey",
		"workspace_id": "WorkspaceID",
		"todo_status": "TodoStatus",
	}
	for input, expected := range tests {
		t.Run(input, func(t *testing.T) {
			assert.Equal(t, expected, toCamelCase(input))
		})
	}
}

// --- Struct output ---

func TestSingularTableNames(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)

	assert.Contains(t, output, "type Todo struct {")
	assert.Contains(t, output, "type Workspace struct {")
	assert.Contains(t, output, "type NoteTag struct {")
	assert.Contains(t, output, "type Author struct {")

	assert.NotContains(t, output, "type Todos struct")
	assert.NotContains(t, output, "type Workspaces struct")
	assert.NotContains(t, output, "type NoteTags struct")
	assert.NotContains(t, output, "type Authors struct")
}

func TestStructsSortedAlphabetically(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)

	idxAuthor := strings.Index(output, "type Author struct {")
	idxNoteTag := strings.Index(output, "type NoteTag struct {")
	idxTodo := strings.Index(output, "type Todo struct {")
	idxWorkspace := strings.Index(output, "type Workspace struct {")

	assert.Greater(t, idxNoteTag, idxAuthor)
	assert.Greater(t, idxTodo, idxNoteTag)
	assert.Greater(t, idxWorkspace, idxTodo)
}

func TestTableComment(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)
	assert.Contains(t, output, "// Author table for book authors\ntype Author struct {")
}

func TestPackageDeclaration(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "mymodels"}, newTestCatalog(), nil, nil)
	assert.Contains(t, output, "// Code generated by pgxgen. DO NOT EDIT.\npackage mymodels\n")
}

// --- Enums ---

func TestEnumsBeforeStructs(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)

	idxLastEnum := strings.Index(output, "func (e TodoStatus) Valid() bool {")
	idxFirstStruct := strings.Index(output, "type Author struct {")

	require.Greater(t, idxLastEnum, 0)
	require.Greater(t, idxFirstStruct, 0)
	assert.Greater(t, idxFirstStruct, idxLastEnum)
}

func TestEnumsSortedAlphabetically(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)

	idxPriority := strings.Index(output, "type PriorityLevel string")
	idxTodo := strings.Index(output, "type TodoStatus string")

	assert.Greater(t, idxTodo, idxPriority)
}

func TestEnumConstants(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)

	assert.Contains(t, output, `TodoStatusPending TodoStatus = "pending"`)
	assert.Contains(t, output, `TodoStatusCompleted TodoStatus = "completed"`)
	assert.Contains(t, output, `TodoStatusCancelled TodoStatus = "cancelled"`)
	assert.Contains(t, output, `PriorityLevelLow PriorityLevel = "low"`)
	assert.Contains(t, output, `PriorityLevelMedium PriorityLevel = "medium"`)
	assert.Contains(t, output, `PriorityLevelHigh PriorityLevel = "high"`)
}

func TestEnumValidMethod(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)

	assert.Contains(t, output, "func (e TodoStatus) Valid() bool {")
	assert.Contains(t, output, "func (e PriorityLevel) Valid() bool {")
}

// --- Field naming ---

func TestIDFieldNaming(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)

	assert.Contains(t, output, "\tID ")
	assert.Contains(t, output, "\tUserID ")
	assert.Contains(t, output, "\tNoteID ")
	assert.Contains(t, output, "\tTagID ")
	assert.Contains(t, output, "\tWorkspaceID ")

	assert.NotContains(t, output, "UserId")
	assert.NotContains(t, output, "NoteId")
	assert.NotContains(t, output, "TagId")
	assert.NotContains(t, output, "WorkspaceId")
}

func TestURLFieldNaming(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)
	assert.Contains(t, output, "\tWebsiteURL ")
	assert.NotContains(t, output, "WebsiteUrl")
}

// --- Tags ---

func TestEmitDbAndJsonTags(t *testing.T) {
	output := render(t, &config.ModelsConfig{
		PackageName:  "models",
		EmitJsonTags: true,
		EmitDbTags:   true,
	}, newTestCatalog(), nil, nil)

	assert.Contains(t, output, "\tID string `db:\"id\" json:\"id\"`")
	assert.Contains(t, output, "\tUserID int64 `db:\"user_id\" json:\"user_id\"`")
	assert.Contains(t, output, "\tCreatedAt time.Time `db:\"created_at\" json:\"created_at\"`")
}

func TestEmitTagsFromSqlcDefaults(t *testing.T) {
	output := render(t,
		&config.ModelsConfig{PackageName: "models"},
		newTestCatalog(),
		nil,
		&config.SqlcDefaultsConfig{EmitDbTags: true, EmitJsonTags: true},
	)

	assert.Contains(t, output, `db:"id" json:"id"`)
	assert.Contains(t, output, `db:"user_id" json:"user_id"`)
}

func TestNoTagsWhenDisabled(t *testing.T) {
	output := render(t, &config.ModelsConfig{PackageName: "models"}, newTestCatalog(), nil, nil)

	assert.NotContains(t, output, `db:"`)
	assert.NotContains(t, output, `json:"`)
}

func TestSqlcColumnOverrideGoStructTag(t *testing.T) {
	output := render(t,
		&config.ModelsConfig{PackageName: "models", EmitDbTags: true, EmitJsonTags: true},
		newTestCatalog(),
		&config.SqlcOverridesConfig{
			Columns: []config.SqlcColumnOverride{
				{Column: "todos.title", GoStructTag: `validate:"required"`},
				{Column: "todos.user_id", GoStructTag: `validate:"required"`},
			},
		},
		nil,
	)

	assert.Contains(t, output, "\tTitle string `db:\"title\" json:\"title\" validate:\"required\"`")
	assert.Contains(t, output, "\tUserID int64 `db:\"user_id\" json:\"user_id\" validate:\"required\"`")
	// description has no validate tag
	assert.Contains(t, output, "\tDescription string `db:\"description\" json:\"description\"`")
}

// --- Type resolution ---

func TestSqlcColumnOverrideGoType(t *testing.T) {
	output := render(t,
		&config.ModelsConfig{PackageName: "models"},
		newTestCatalog(),
		&config.SqlcOverridesConfig{
			Columns: []config.SqlcColumnOverride{
				{Column: "todos.status", GoType: map[string]interface{}{"type": "TodoStatusType"}},
			},
		},
		nil,
	)

	assert.Contains(t, output, "\tStatus TodoStatusType\n")
}

func TestSqlcTypeOverrideWithImport(t *testing.T) {
	cat := &catalog.Catalog{
		DefaultSchema: "main",
		Schemas: []*catalog.Schema{{
			Name: "main",
			Tables: []*catalog.Table{{
				Name: "items",
				Columns: []*catalog.Column{
					{Name: "id", Type: "TEXT", NotNull: true},
					{Name: "data", Type: "JSONB", NotNull: true},
				},
			}},
		}},
	}

	output := render(t,
		&config.ModelsConfig{PackageName: "models"},
		cat,
		&config.SqlcOverridesConfig{
			Types: []config.SqlcTypeOverride{
				{
					DbType: "JSONB",
					GoType: map[string]interface{}{
						"type":   "JSONField",
						"import": "github.com/example/store/storecmn",
					},
				},
			},
		},
		nil,
	)

	assert.Contains(t, output, "\tData storecmn.JSONField\n")
}

func TestModelTypeOverrides(t *testing.T) {
	cat := &catalog.Catalog{
		DefaultSchema: "main",
		Schemas: []*catalog.Schema{{
			Name: "main",
			Tables: []*catalog.Table{{
				Name: "events",
				Columns: []*catalog.Column{
					{Name: "id", Type: "TEXT", NotNull: true},
					{Name: "happened_at", Type: "TIMESTAMPTZ", NotNull: true},
				},
			}},
		}},
	}

	output := render(t,
		&config.ModelsConfig{
			PackageName: "models",
			TypeOverrides: []config.TypeOverrideConfig{
				{SqlType: "TIMESTAMPTZ", GoType: "time.Time"},
			},
		},
		cat, nil, nil,
	)

	assert.Contains(t, output, "\tHappenedAt time.Time\n")
}

// --- Nullable types ---

func TestNullableTypesPointers(t *testing.T) {
	output := render(t,
		&config.ModelsConfig{PackageName: "models", ReplaceNullableTypes: true},
		newTestCatalog(), nil, nil,
	)

	assert.Contains(t, output, "\tCompletedAt *time.Time\n")
	assert.Contains(t, output, "\tWorkspaceID *string\n")
	assert.NotContains(t, output, "sql.NullTime")
	assert.NotContains(t, output, "sql.NullString")
}

func TestNullableTypesDefault(t *testing.T) {
	output := render(t,
		&config.ModelsConfig{PackageName: "models"},
		newTestCatalog(), nil, nil,
	)

	assert.Contains(t, output, "\tCompletedAt sql.NullTime\n")
	assert.Contains(t, output, "\tWorkspaceID sql.NullString\n")
}
